# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: wltk157的空间(BETA)
email: wltk157@vip.qq.com
description: > # this means to ignore newlines until "baseurl:"
  Powered by Jekyll and Github Pages!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://wltk157.github.io" # the base hostname & protocol for your site
twitter_username: wltk158
github_username:  wltk157

# Build settings
markdown: kramdown
